services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    build: ./backend
    ports:
      - "5213:5213"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=bankdb;Username=user;Password=password
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./backend/Statements.WebAPI:/app
      - backend-bin:/app/bin
      - backend-obj:/app/obj

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres-data:
  backend-bin:
  backend-obj:
  pgadmin-data:
